module.exports = {
  UserModel: "users",
  TrialUserModel: "trialusers",
  TempUserModel: "tempuser",
  CategoryModel: "category",
  SubCategoryModel: "subcategory",
  ProductModel: "product",
  UserSubscriptionModel: "subscription",
  subscriptionPlanModel: "subscriptionplan",
  SubscriptionCheckOutModel: "subscriptioncheckout",
  BikeBrandModel: "bikebrand",
  BikeModelModel: "bikemodel",
  BikeModel: "bikedetails",
  TruckBrandModel: "truckbrand",
  TruckModelModel: "truckmodel",
  TruckDetailModel: "truckdetails",
  TruckDriverDocModel: "truckdriverdoc",
  TruckDriverAddressModel: "truckdriveraddress",
  TruckDriverBankDetailsModel: "truckdriverbankdetails",
  TruckDriverModel: "truckdriverdetails",
  AssignTruckForDriverModel: "assigntruckfordriverdetails",
  AssignZoneForAssignTruckModel: "assignzoneforassigntruckdetails",
  AssignUserAddressForBikeDriverModel: "assignuseraddressforbikedriverdetails",
  BikeDriverModel: "bikedriverdetails",
  DriverBankDetailsModel: "driverbankdetails",
  DriverAddressModel: "driveraddress",
  DriverDocModel: "driverdoc",
  UserAddressModel: "useraddress",
  ProductCheckOutModel: "productcheckout",
  DeliveryLocationModel: "deliverylocation",
  ProductOrderModel: "productorder",
  VatModel: "vat",
  CartModel : "cart",
  DeliveryZoneModel : "deliveryzone"
};
